name: Latest stack overflow activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-dev:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jstellmacher/blog-post-workflow@master
        with:
          comment_tag_name: "Dev.to"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://dev.to/feed/jstellmacher"
